# coding: utf-8

"""
    Sev Data flex API v1.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CustKwhMeteresReading(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'meter_id': 'str',
        'readings': 'list[CustKwhReading]'
    }

    attribute_map = {
        'meter_id': 'meter_id',
        'readings': 'readings'
    }

    def __init__(self, meter_id=None, readings=None):  # noqa: E501
        """CustKwhMeteresReading - a model defined in Swagger"""  # noqa: E501
        self._meter_id = None
        self._readings = None
        self.discriminator = None
        if meter_id is not None:
            self.meter_id = meter_id
        if readings is not None:
            self.readings = readings

    @property
    def meter_id(self):
        """Gets the meter_id of this CustKwhMeteresReading.  # noqa: E501


        :return: The meter_id of this CustKwhMeteresReading.  # noqa: E501
        :rtype: str
        """
        return self._meter_id

    @meter_id.setter
    def meter_id(self, meter_id):
        """Sets the meter_id of this CustKwhMeteresReading.


        :param meter_id: The meter_id of this CustKwhMeteresReading.  # noqa: E501
        :type: str
        """

        self._meter_id = meter_id

    @property
    def readings(self):
        """Gets the readings of this CustKwhMeteresReading.  # noqa: E501


        :return: The readings of this CustKwhMeteresReading.  # noqa: E501
        :rtype: list[CustKwhReading]
        """
        return self._readings

    @readings.setter
    def readings(self, readings):
        """Sets the readings of this CustKwhMeteresReading.


        :param readings: The readings of this CustKwhMeteresReading.  # noqa: E501
        :type: list[CustKwhReading]
        """

        self._readings = readings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustKwhMeteresReading, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustKwhMeteresReading):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
