# coding: utf-8

"""
    Sev Data flex API v1.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.esitmated_cost_per_meter import EsitmatedCostPerMeter  # noqa: E501
from swagger_client.rest import ApiException


class TestEsitmatedCostPerMeter(unittest.TestCase):
    """EsitmatedCostPerMeter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEsitmatedCostPerMeter(self):
        """Test EsitmatedCostPerMeter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.esitmated_cost_per_meter.EsitmatedCostPerMeter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
