# coding: utf-8

"""
    Sev Data flex API v1.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.login_input import LoginInput  # noqa: E501
from swagger_client.rest import ApiException


class TestLoginInput(unittest.TestCase):
    """LoginInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginInput(self):
        """Test LoginInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.login_input.LoginInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
