# coding: utf-8

"""
    Sev Data flex API v1.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.customer_rest_api_api import CustomerRESTApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomerRESTApiApi(unittest.TestCase):
    """CustomerRESTApiApi unit test stubs"""

    def setUp(self):
        self.api = CustomerRESTApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_customer_rest_api_estimated_co2_post(self):
        """Test case for api_customer_rest_api_estimated_co2_post

        """
        pass

    def test_api_customer_rest_api_estimated_cost_post(self):
        """Test case for api_customer_rest_api_estimated_cost_post

        """
        pass

    def test_api_customer_rest_api_get_available_meters_post(self):
        """Test case for api_customer_rest_api_get_available_meters_post

        """
        pass

    def test_api_customer_rest_api_hourly_kwh_usage_post(self):
        """Test case for api_customer_rest_api_hourly_kwh_usage_post

        """
        pass

    def test_api_customer_rest_api_login_and_get_jwt_token_post(self):
        """Test case for api_customer_rest_api_login_and_get_jwt_token_post

        """
        pass

    def test_api_customer_rest_api_refresh_jwt_key_token_post(self):
        """Test case for api_customer_rest_api_refresh_jwt_key_token_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
