/*
 * Sev Data flex API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CustDKRReading
    /// </summary>
    [DataContract(Name = "CustDKRReading")]
    public partial class CustDKRReading : IEquatable<CustDKRReading>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustDKRReading" /> class.
        /// </summary>
        /// <param name="timeStamp">timeStamp.</param>
        /// <param name="reading">reading.</param>
        /// <param name="unit">unit.</param>
        /// <param name="priceUnit">priceUnit.</param>
        /// <param name="tarif">tarif.</param>
        public CustDKRReading(DateTime timeStamp = default(DateTime), double reading = default(double), string unit = default(string), double priceUnit = default(double), int tarif = default(int))
        {
            this.TimeStamp = timeStamp;
            this.Reading = reading;
            this.Unit = unit;
            this.PriceUnit = priceUnit;
            this.Tarif = tarif;
        }

        /// <summary>
        /// Gets or Sets TimeStamp
        /// </summary>
        [DataMember(Name = "time_stamp", EmitDefaultValue = false)]
        public DateTime TimeStamp { get; set; }

        /// <summary>
        /// Gets or Sets Reading
        /// </summary>
        [DataMember(Name = "reading", EmitDefaultValue = false)]
        public double Reading { get; set; }

        /// <summary>
        /// Gets or Sets Unit
        /// </summary>
        [DataMember(Name = "unit", EmitDefaultValue = true)]
        public string Unit { get; set; }

        /// <summary>
        /// Gets or Sets PriceUnit
        /// </summary>
        [DataMember(Name = "price_unit", EmitDefaultValue = false)]
        public double PriceUnit { get; set; }

        /// <summary>
        /// Gets or Sets Tarif
        /// </summary>
        [DataMember(Name = "tarif", EmitDefaultValue = false)]
        public int Tarif { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustDKRReading {\n");
            sb.Append("  TimeStamp: ").Append(TimeStamp).Append("\n");
            sb.Append("  Reading: ").Append(Reading).Append("\n");
            sb.Append("  Unit: ").Append(Unit).Append("\n");
            sb.Append("  PriceUnit: ").Append(PriceUnit).Append("\n");
            sb.Append("  Tarif: ").Append(Tarif).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CustDKRReading);
        }

        /// <summary>
        /// Returns true if CustDKRReading instances are equal
        /// </summary>
        /// <param name="input">Instance of CustDKRReading to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CustDKRReading input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TimeStamp == input.TimeStamp ||
                    (this.TimeStamp != null &&
                    this.TimeStamp.Equals(input.TimeStamp))
                ) && 
                (
                    this.Reading == input.Reading ||
                    this.Reading.Equals(input.Reading)
                ) && 
                (
                    this.Unit == input.Unit ||
                    (this.Unit != null &&
                    this.Unit.Equals(input.Unit))
                ) && 
                (
                    this.PriceUnit == input.PriceUnit ||
                    this.PriceUnit.Equals(input.PriceUnit)
                ) && 
                (
                    this.Tarif == input.Tarif ||
                    this.Tarif.Equals(input.Tarif)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TimeStamp != null)
                {
                    hashCode = (hashCode * 59) + this.TimeStamp.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Reading.GetHashCode();
                if (this.Unit != null)
                {
                    hashCode = (hashCode * 59) + this.Unit.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.PriceUnit.GetHashCode();
                hashCode = (hashCode * 59) + this.Tarif.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
