/*
 * Sev Data flex API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerWithInstallations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerWithInstallationsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerWithInstallations
        //private CustomerWithInstallations instance;

        public CustomerWithInstallationsTests()
        {
            // TODO uncomment below to create an instance of CustomerWithInstallations
            //instance = new CustomerWithInstallations();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerWithInstallations
        /// </summary>
        [Fact]
        public void CustomerWithInstallationsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerWithInstallations
            //Assert.IsType<CustomerWithInstallations>(instance);
        }


        /// <summary>
        /// Test the property 'CustomerName'
        /// </summary>
        [Fact]
        public void CustomerNameTest()
        {
            // TODO unit test for the property 'CustomerName'
        }
        /// <summary>
        /// Test the property 'Installations'
        /// </summary>
        [Fact]
        public void InstallationsTest()
        {
            // TODO unit test for the property 'Installations'
        }

    }

}
