/*
 * Sev Data flex API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CustKwhReading
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustKwhReadingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustKwhReading
        //private CustKwhReading instance;

        public CustKwhReadingTests()
        {
            // TODO uncomment below to create an instance of CustKwhReading
            //instance = new CustKwhReading();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustKwhReading
        /// </summary>
        [Fact]
        public void CustKwhReadingInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustKwhReading
            //Assert.IsType<CustKwhReading>(instance);
        }


        /// <summary>
        /// Test the property 'TimeStamp'
        /// </summary>
        [Fact]
        public void TimeStampTest()
        {
            // TODO unit test for the property 'TimeStamp'
        }
        /// <summary>
        /// Test the property 'Reading'
        /// </summary>
        [Fact]
        public void ReadingTest()
        {
            // TODO unit test for the property 'Reading'
        }
        /// <summary>
        /// Test the property 'CumulativeValue'
        /// </summary>
        [Fact]
        public void CumulativeValueTest()
        {
            // TODO unit test for the property 'CumulativeValue'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Fact]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }

    }

}
