/*
 * Sev Data flex API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CustInstallation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustInstallationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustInstallation
        //private CustInstallation instance;

        public CustInstallationTests()
        {
            // TODO uncomment below to create an instance of CustInstallation
            //instance = new CustInstallation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustInstallation
        /// </summary>
        [Fact]
        public void CustInstallationInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustInstallation
            //Assert.IsType<CustInstallation>(instance);
        }


        /// <summary>
        /// Test the property 'MoveInDate'
        /// </summary>
        [Fact]
        public void MoveInDateTest()
        {
            // TODO unit test for the property 'MoveInDate'
        }
        /// <summary>
        /// Test the property 'MoveOnDate'
        /// </summary>
        [Fact]
        public void MoveOnDateTest()
        {
            // TODO unit test for the property 'MoveOnDate'
        }
        /// <summary>
        /// Test the property 'InstId'
        /// </summary>
        [Fact]
        public void InstIdTest()
        {
            // TODO unit test for the property 'InstId'
        }
        /// <summary>
        /// Test the property 'InstNickname'
        /// </summary>
        [Fact]
        public void InstNicknameTest()
        {
            // TODO unit test for the property 'InstNickname'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Floor'
        /// </summary>
        [Fact]
        public void FloorTest()
        {
            // TODO unit test for the property 'Floor'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'PostalDistrict'
        /// </summary>
        [Fact]
        public void PostalDistrictTest()
        {
            // TODO unit test for the property 'PostalDistrict'
        }
        /// <summary>
        /// Test the property 'TarifNumber'
        /// </summary>
        [Fact]
        public void TarifNumberTest()
        {
            // TODO unit test for the property 'TarifNumber'
        }
        /// <summary>
        /// Test the property 'BillingType'
        /// </summary>
        [Fact]
        public void BillingTypeTest()
        {
            // TODO unit test for the property 'BillingType'
        }
        /// <summary>
        /// Test the property 'Meters'
        /// </summary>
        [Fact]
        public void MetersTest()
        {
            // TODO unit test for the property 'Meters'
        }

    }

}
