/*
 * Sev Data flex API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CustDKRReading
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustDKRReadingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustDKRReading
        //private CustDKRReading instance;

        public CustDKRReadingTests()
        {
            // TODO uncomment below to create an instance of CustDKRReading
            //instance = new CustDKRReading();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustDKRReading
        /// </summary>
        [Fact]
        public void CustDKRReadingInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustDKRReading
            //Assert.IsType<CustDKRReading>(instance);
        }


        /// <summary>
        /// Test the property 'TimeStamp'
        /// </summary>
        [Fact]
        public void TimeStampTest()
        {
            // TODO unit test for the property 'TimeStamp'
        }
        /// <summary>
        /// Test the property 'Reading'
        /// </summary>
        [Fact]
        public void ReadingTest()
        {
            // TODO unit test for the property 'Reading'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Fact]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
        /// <summary>
        /// Test the property 'PriceUnit'
        /// </summary>
        [Fact]
        public void PriceUnitTest()
        {
            // TODO unit test for the property 'PriceUnit'
        }
        /// <summary>
        /// Test the property 'Tarif'
        /// </summary>
        [Fact]
        public void TarifTest()
        {
            // TODO unit test for the property 'Tarif'
        }

    }

}
