/*
 * Sev Data flex API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CustKwhMeteresReading
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustKwhMeteresReadingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustKwhMeteresReading
        //private CustKwhMeteresReading instance;

        public CustKwhMeteresReadingTests()
        {
            // TODO uncomment below to create an instance of CustKwhMeteresReading
            //instance = new CustKwhMeteresReading();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustKwhMeteresReading
        /// </summary>
        [Fact]
        public void CustKwhMeteresReadingInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustKwhMeteresReading
            //Assert.IsType<CustKwhMeteresReading>(instance);
        }


        /// <summary>
        /// Test the property 'MeterId'
        /// </summary>
        [Fact]
        public void MeterIdTest()
        {
            // TODO unit test for the property 'MeterId'
        }
        /// <summary>
        /// Test the property 'Readings'
        /// </summary>
        [Fact]
        public void ReadingsTest()
        {
            // TODO unit test for the property 'Readings'
        }

    }

}
