/*
 * Sev Data flex API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CustMeter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustMeterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustMeter
        //private CustMeter instance;

        public CustMeterTests()
        {
            // TODO uncomment below to create an instance of CustMeter
            //instance = new CustMeter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustMeter
        /// </summary>
        [Fact]
        public void CustMeterInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustMeter
            //Assert.IsType<CustMeter>(instance);
        }


        /// <summary>
        /// Test the property 'MeterId'
        /// </summary>
        [Fact]
        public void MeterIdTest()
        {
            // TODO unit test for the property 'MeterId'
        }
        /// <summary>
        /// Test the property 'MeterNickname'
        /// </summary>
        [Fact]
        public void MeterNicknameTest()
        {
            // TODO unit test for the property 'MeterNickname'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Fact]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }
        /// <summary>
        /// Test the property 'MeterName'
        /// </summary>
        [Fact]
        public void MeterNameTest()
        {
            // TODO unit test for the property 'MeterName'
        }
        /// <summary>
        /// Test the property 'MeterType'
        /// </summary>
        [Fact]
        public void MeterTypeTest()
        {
            // TODO unit test for the property 'MeterType'
        }
        /// <summary>
        /// Test the property 'InstallDate'
        /// </summary>
        [Fact]
        public void InstallDateTest()
        {
            // TODO unit test for the property 'InstallDate'
        }
        /// <summary>
        /// Test the property 'RemovalDate'
        /// </summary>
        [Fact]
        public void RemovalDateTest()
        {
            // TODO unit test for the property 'RemovalDate'
        }

    }

}
