/*
 * Sev Data flex API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing EsitmatedCostPerMeter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EsitmatedCostPerMeterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EsitmatedCostPerMeter
        //private EsitmatedCostPerMeter instance;

        public EsitmatedCostPerMeterTests()
        {
            // TODO uncomment below to create an instance of EsitmatedCostPerMeter
            //instance = new EsitmatedCostPerMeter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EsitmatedCostPerMeter
        /// </summary>
        [Fact]
        public void EsitmatedCostPerMeterInstanceTest()
        {
            // TODO uncomment below to test "IsType" EsitmatedCostPerMeter
            //Assert.IsType<EsitmatedCostPerMeter>(instance);
        }


        /// <summary>
        /// Test the property 'MeterId'
        /// </summary>
        [Fact]
        public void MeterIdTest()
        {
            // TODO unit test for the property 'MeterId'
        }
        /// <summary>
        /// Test the property 'Readings'
        /// </summary>
        [Fact]
        public void ReadingsTest()
        {
            // TODO unit test for the property 'Readings'
        }

    }

}
