/*
 * Sev Data flex API v1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing FilterCustKwhMeteresReading
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FilterCustKwhMeteresReadingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FilterCustKwhMeteresReading
        //private FilterCustKwhMeteresReading instance;

        public FilterCustKwhMeteresReadingTests()
        {
            // TODO uncomment below to create an instance of FilterCustKwhMeteresReading
            //instance = new FilterCustKwhMeteresReading();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FilterCustKwhMeteresReading
        /// </summary>
        [Fact]
        public void FilterCustKwhMeteresReadingInstanceTest()
        {
            // TODO uncomment below to test "IsType" FilterCustKwhMeteresReading
            //Assert.IsType<FilterCustKwhMeteresReading>(instance);
        }


        /// <summary>
        /// Test the property 'Meters'
        /// </summary>
        [Fact]
        public void MetersTest()
        {
            // TODO unit test for the property 'Meters'
        }
        /// <summary>
        /// Test the property 'FromDate'
        /// </summary>
        [Fact]
        public void FromDateTest()
        {
            // TODO unit test for the property 'FromDate'
        }
        /// <summary>
        /// Test the property 'ToDate'
        /// </summary>
        [Fact]
        public void ToDateTest()
        {
            // TODO unit test for the property 'ToDate'
        }

    }

}
